# Generated by Django 4.1 on 2022-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Время готовки'),
        ),
    ]
