# Generated by Django 4.1 on 2022-08-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
    ]
