# Generated by Django 4.1 on 2022-09-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription_delete_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
